### ISSUE TITLE
[Bug] realbasicvsr failed to run pytorch2onnx

### ISSUE THREAD

**Issue by Winnie202** [open-mmlab/mmediting#1295]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmediting).

### Task

I have modified the scripts/configs or I'm working on my own tasks/models/datasets.

### Environment

![Uploading 2022-10-13 19-38-42屏幕截图.png…]()

### Reproduces the problem - code sample

python tools/pytorch2onnx.py \ 
configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py  \
    work_file/iter_305000.pth  \
    restorer  \
    data/demo_test/biccubic/001  \
    --output-file tmp.onnx \
    --show \
    --verify 

### Reproduces the problem - command or script

python tools/pytorch2onnx.py \ 
configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py  \
    work_file/iter_305000.pth  \
    restorer  \
    data/demo_test/biccubic/001  \
    --output-file tmp.onnx \
    --show \
    --verify 

### Reproduces the problem - error message

![Uploading 2022-10-13 19-30-01屏幕截图.png…]()
![2022-10-13 19-30-19屏幕截图](https://user-images.githubusercontent.com/86768013/195587754-665cbaf8-4852-43ac-85d0-f8962f9a9249.png)

**Comment by Z-Fran** [comment]
pytorch2onnx in `master` branch doesn't support vsr models now. You can using MMEditing 2.0, by checkout 1.x branch. You can reference [documents]().
You can using following script:

**Comment by Z-Fran** [comment]
I think this is because not setting frames length. Too long frames result in waiting as picture showing. pytorch2onnx in `master` branch doesn't support vsr models well now. You can using MMEditing 2.0, by checkout 1.x branch. You can reference [documents](https://mmediting.readthedocs.io/en/1.x/).
You can using following script:
```
python tools/model_converters/pytorch2onnx.py configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py  realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds_20211027-0e2ff207.pth video_restorer data/Vid4/BDx4/calendar --num-frames=15 --sequence_length=15
```
Without setting num-frames=15 and longer frames will result in long time waiting. 

Simply, you can reference version 2.0 code [mmediting/pytorch2onnx.py at 1.x · open-mmlab/mmediting](https://github.com/open-mmlab/mmediting/blob/1.x/tools/model_converters/pytorch2onnx.py) to support vsr models in master branch. Add welcome yor contribution to MMEditing.

**Comment by zengyh1900** [comment]
Fixed in https://github.com/open-mmlab/mmediting/pull/1300
