### ISSUE TITLE
Training details of inpainting models on CelebA-HQ

### ISSUE THREAD

**Issue by fenglinglwb** [open-mmlab/mmediting#259]
Is it necessary to perform random cropping augmentation during training of inpainting models on CelebA-HQ? The given config files say yes, but in my understanding, they shouldn't include this operation.

Besides, it's said that we only need 20K training iters for DeepFillV2 on CelebA-HQ (https://mmediting.readthedocs.io/en/latest/inpainting_models.html), which is inconsistent with the released log. So, how many iterations do we need to train DeepFillV2 under the setting of 8 GPUs and 2 samples per GPU?

Thanks.

**Comment by nbei** [comment]
In fact, the random cropping will not crop the images in CelebA-HQ. Because we directly use the 256x256 dataset for training.
For the training iterations, it seems that we put the wrong log file. The results reported in our repo is for 20k training and we will check the experiments later and update the log file.
