### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by flynnamy** [open-mmlab/mmediting#616]
Hi，it has an error when I do inference of restoration_face_demo like following img. It seems that does not support doing inference of single image. How to solve this? @ckkelvinchan 
![image](https://user-images.githubusercontent.com/20398890/142558028-820f699a-4ea6-4165-887b-9949e7211a9d.png)

**Comment by ckkelvinchan** [comment]
Could you provide me with the command you used?

**Comment by flynnamy** [comment]
I use this command:python demo/restoration_face_demo.py configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py glean_in128out1024_4x2_300k_ffhq_celebahq_20210812-acbcb04f.pth tests/data/face/000001.png results/000001.png --upscale_factor 4,any suggestion? @ckkelvinchan

**Comment by ckkelvinchan** [comment]
I just did a little investigation and it seems that the problem comes from `target_size`. Could you try changing the `target_size` [here](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py#L139) from a list to tuple (e.g. `[128, 128]` -> `(128, 128)`).

But interestingly I did not see this error before.

**Comment by flynnamy** [comment]
Yeah,I modify this and it works. It seems the type should be tuple, Thanks!

**Comment by ckkelvinchan** [comment]
> Yeah,I modify this and it works. It seems the type should be tuple, Thanks!

That's strange. I did not encounter this error before. Anyway, I will fix this. Thank you for letting us know!
