### ISSUE TITLE
Various pytorch version comparisons return the wrong result with pytorch >= 1.10

### ISSUE THREAD

**Issue by Juggernaut93** [open-mmlab/mmediting#722]
Various functions use the string comparison `torch.__version__ > 'x.y'` in order to determine if the current version of pytorch is higher than a certain version. However, this returns an incorrect result when `torch.__version__` is greater or equal than 1.10.

Examples of this issue are [here](https://github.com/open-mmlab/mmediting/blob/master/tools/publish_model.py#L24), [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/builder.py#L145) and [here](https://github.com/open-mmlab/mmediting/blob/master/tests/test_runtime/test_ema_hook.py#L16).

This results, for example, in `persistent_workers` not being set to True when creating a DataLoader in pytorch 1.10.

**Comment by wangruohui** [comment]
Thank you for pointing this out. 
A simple solution would be following [this](https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python) to use `package.version.parse`. Otherwise, we need to set up a new function dedicated to this functionality.

Would you like to contribute to us by solving this issue? We really appreciate that.

**Comment by Juggernaut93** [comment]
Hi, I will be able to make a pull request on the next Monday.

**Comment by Juggernaut93** [comment]
I have created a pull request to fix the issue: #723

**Comment by wangruohui** [comment]
Fixed with #723
