### ISSUE TITLE
[demo args] Fix demo args as to use '-' instead of '_'?

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmediting#804]
In mmdet, maintainers recommend to use '-' for argparse arguments.
https://github.com/open-mmlab/mmdetection/pull/6734#discussion_r767377634

But in mmediting demos, there are some arguments to use '_' instead of '-'.
https://github.com/open-mmlab/mmediting/blob/7cb8153d9d95a6926b4ce85916307484661ed719/demo/restoration_demo.py#L22

Should it be fixed to use hyphen?

**Comment by Yshuo-Li** [comment]
I'm sorry that we used the connector incorrectly. Could you please fix the typo with a pull request?

**Comment by wangruohui** [comment]
And this will break backward compatibility, scripts written for previous versions reports error. 
I think we need to add some deprecation warnings at least. need modification 

Second, It seems to be a big modification because we also need to modify documentation to make it consistent. We can search all regex "--\w+_" patterns within docs/demo and maybe even tools folder.

**Comment by wangruohui** [comment]
A big issue is that this modification will break backward compatibility, scripts written for previous versions reports error.
I think we need to add some deprecation warnings at least. need modification

Second, It seems to be a big modification because we also need to modify documentation to make it consistent. We can search all regex "--\w+_" patterns within docs/demo and maybe even tools folder.
