### ISSUE TITLE
[Enhance] Evaluation before training

### ISSUE THREAD

**Issue by ryanxingql** [open-mmlab/mmediting#874]
Hi,
I notice that the MMCV supports evaluation before training in its evaluation hook by setting a [`start` indicator](https://github.com/open-mmlab/mmcv/blob/9f5a03dc2ca3731b2c1b18f90f826fcb9eb51ccf/mmcv/runner/hooks/evaluation.py#L25).
This feature is very useful for us to check the performance baseline.
It seems that our hook does not support this feature.
May I try to support this by PR? Thanks.

**Comment by wangruohui** [comment]
Do you mean a situation where you start from a pre-trained checkpoint and hope for a performance indicator before any optimization starts?

**Comment by wangruohui** [comment]
Sure, we welcome contributors!

The difference of EvalHook between MMCV and MMEditing is probably due to a historical reason, and a preference between `EpochBasedRunner` and `IterBasedRunner` for high or low-level tasks. 

You can port some features from MMCV, just make sure the default setting does not change the behavior of existing config files.

**Comment by ryanxingql** [comment]
> Do you mean a situation where you start from a pre-trained checkpoint and hope for a performance indicator before any optimization starts?

Besides this, I want to run the evaluation between LQ and GT before training. Is there any way to do this?

**Comment by wangruohui** [comment]
You can try tools/tests.py, this is for evaluation purpose given prediction and GT.
Here you just pretend LQ to be the prediction, and run the program.

**Comment by ryanxingql** [comment]
Thank you so much~
